const WHATSAPP_NUMBER="919010185837", RESTAURANT_NAME="Food On Wheels";
const menuData=[
["Burger Combo",[["Veg Burger + Fries + Mojito",110],["Veg Burger + Fries + Mojito + 2 Fingers",170],["Paneer Burger + Mojito",160],["Egg Burger + Fries + Mojito",150],["Classic Chicken Burger + Fries + Mojito",170],["Crispy Chicken Burger + Mojito or Fries",160],["Crispy Chicken Burger + Fries + Mojito",180],["SPL Chicken Burger + Fries + Mojito",230]]],
["Rolls Combo",[["Veg Roll + Fries + Mojito + 2 Fingers",170],["Paneer Roll + Mojito or Fries",160],["Egg Roll + Fries + Mojito",170],["Crispy Chicken Roll + Fries or Mojito",160],["Crispy Chicken Roll + Fries + Mojito + 2pcs Chicken Lollipop",210],["Popcorn Chicken Roll + Mojito",200]]],
["Sandwich Combo",[["Mix Veg Sandwich + Fries + Mojito + Cheese & Corn Nuggets (3pcs)",190],["Corn & Cheese Sandwich + Fries + Mojito",170],["Chicken Sandwich + Fries + Mojito + 2 Fingers + 2 Lollipops",240],["Chicken Cheese Sandwich + Fries + Mojito + 2 Lollipops",270]]],
["French Fries",[["Mini Fries",49],["Salted Fries",70],["Peri Peri Fries",75],["Salted Cheesy Fries",90],["Peri Peri Cheesy Fries",99],["Paneer Loaded Fries",129],["Chicken Loaded Fries",139],["Cheesy Chicken Loaded Fries",149]]],
["Burgers",[["Veg Burger",70],["Paneer Burger",100],["Egg Burger",75],["Egg Chicken Burger",109],["Classic Chicken Burger",95],["Chicken Crispy Burger",110],["Popcorn Chicken Burger",100],["SPL Chicken Burger",120],["SPL Chicken Burger with Cheese",140],["Crispy No Bun Chicken Burger",179]]],
["Rolls",[["Veg Roll",70],["Paneer Roll",100],["Egg Roll",75],["Egg Chicken Roll",100],["Crispy Chicken Roll",110],["Popcorn Chicken Roll",100],["SPL Chicken Roll",120]]],
["Bread Omelette",[["Bread Omelette",70],["Bread Omelette with Cheese",89],["Egg Chicken Bread Omelette",110],["Egg Chicken Bread Omelette with Cheese",129]]],
["Pav Bajji",[["Mushroom Pav Bajji",110],["Paneer Pav Bajji",129],["Egg Pav Bajji",110],["Chicken Pav Bajji",129],["Egg Chicken Pav Bajji",149]]],
["Starters",[["Veg Fingers (6)",79],["Paneer Popcorn (100gms)",119],["Paneer Fingers (6)",119],["Cheese Corn Nuggets (6)",99],["Chicken Nuggets (6)",89],["Chicken Fingers (6)",99],["Chicken Cheese Balls (6)",110],["Chicken Popcorn (130gms)",120],["Crispy Chicken Lollipop (5)",110],["Chicken Lollipop (Kabab Style)",110],["Crispy Chicken Chips",139],["Crispy Chicken Fries",139]]],
["Pizzas",[["Cheese Blast",99],["Cheese & Corn Pizza",120],["Mushroom Pizza",120],["Paneer Pizza",130],["Paneer Corn Pizza",140],["Chicken Pizza",140],["Chicken Keema Pizza",160],["Chicken Corn Pizza",150]]],
["Sandwich Menu",[["Mix Veg Sandwich",80],["Corn & Cheese Sandwich",90],["Mushroom Sandwich",100],["Paneer Sandwich",100],["Paneer Cheese Sandwich",120],["Chicken Sandwich",120],["Chicken & Cheese Sandwich",140],["Crispy Chicken Sandwich",120]]],
["Devil Eggs",[["Crispy Devil Eggs - Green Masala (6)",120],["Crispy Devil Eggs - Thadoori Masala (6)",120]]],
["Mojito's",[["Lemon Sprite",59],["Lemon Mint",69],["Blue Coraco",69],["Strawberry",69],["Pinacola",69]]]
];
const imageMap={Burgers:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80","French Fries":"https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80",Pizzas:"https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80",Starters:"https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80","Rolls Combo":"https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=600&q=80","Mojito's":"https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=600&q=80"};
const fallback=["https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80","https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=600&q=80"];
let orderType="dining",cart={};
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const menu=menuData.map(([name,items])=>({name,items:items.map(([n,p])=>({name:n,price:p,id:slug(name+"-"+n),diningOnly:name.includes("Combo")}))}));
const allItems=()=>menu.flatMap(c=>c.items), item=id=>allItems().find(x=>x.id===id);
function imgFor(cat,i){return imageMap[cat]||fallback[i%fallback.length]}
function renderMenu(){
 const cats=document.getElementById("categories"), box=document.getElementById("menu");
 cats.innerHTML=menu.map((c,i)=>`<button class="chip ${i===0?"active":""}" onclick="jump('${slug(c.name)}',this)">${c.name}</button>`).join("");
 box.innerHTML=menu.map((c,ci)=>`<section class="category" id="cat-${slug(c.name)}"><h2>${c.name}</h2><div class="item-grid">${c.items.map((i,ii)=>`<article class="item"><div class="food-img" style="background-image:url('${imgFor(c.name,ii)}')"></div><div class="info"><h3>${i.name}${i.diningOnly?'<span class="tag">DINING</span>':''}</h3><div class="price">₹${i.price}</div></div><div class="action" id="act-${i.id}"></div></article>`).join("")}</div></section>`).join("");
 allItems().forEach(i=>renderAction(i.id));
}
function jump(id,el){document.getElementById("cat-"+id)?.scrollIntoView({behavior:"smooth"});document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));el?.classList.add("active")}
function renderAction(id){const el=document.getElementById("act-"+id),q=cart[id]||0;if(!el)return;el.innerHTML=q?`<div class="qty"><button onclick="changeQty('${id}',-1)">−</button><b>${q}</b><button onclick="changeQty('${id}',1)">+</button></div>`:`<button class="add" onclick="changeQty('${id}',1)">ADD +</button>`}
function changeQty(id,n){const i=item(id);if(orderType==="parcel"&&i.diningOnly&&n>0){alert("This combo is available for dining only.");return}cart[id]=Math.max(0,(cart[id]||0)+n);if(!cart[id])delete cart[id];renderAction(id);updateCart()}
function totals(){let count=0,food=0;Object.entries(cart).forEach(([id,q])=>{food+=item(id).price*q;count+=q});const parcel=orderType==="parcel"&&count?10:0;return{count,food,parcel,total:food+parcel}}
function updateCart(){const t=totals(),bar=document.getElementById("cartBar");bar.hidden=!t.count;document.getElementById("cartCount").textContent=t.count;document.getElementById("cartItemsCount").textContent=`${t.count} ${t.count===1?"item":"items"}`;document.getElementById("cartTotal").textContent=t.total;document.getElementById("foodTotal").textContent=t.food;document.getElementById("modalTotal").textContent=t.total;document.getElementById("parcelLine").hidden=!t.parcel}
function openCart(){const box=document.getElementById("cartItems");box.innerHTML=Object.entries(cart).map(([id,q])=>{const i=item(id);return `<div class="cart-row"><div><b>${i.name}</b><small>₹${i.price} × ${q}</small></div><div class="row-actions"><button onclick="changeQty('${id}',-1)">−</button><b>${q}</b><button onclick="changeQty('${id}',1)">+</button></div></div>`}).join("");document.getElementById("cartModal").hidden=false}
function closeCart(){document.getElementById("cartModal").hidden=true}
function setType(type){orderType=type;document.querySelectorAll(".type").forEach(b=>b.classList.toggle("active",b.dataset.type===type));if(type==="parcel")Object.keys(cart).forEach(id=>{if(item(id)?.diningOnly)delete cart[id]});allItems().forEach(i=>renderAction(i.id));updateCart()}
async function sendWhatsApp(){const t=totals();if(!t.count)return alert("Please add at least one item.");const items=Object.entries(cart).map(([id,q])=>{const i=item(id);return{name:i.name,quantity:q,unitPrice:i.price,lineTotal:i.price*q}});const btn=document.getElementById("whatsappButton");btn.disabled=true;btn.textContent="Generating order…";try{const r=await fetch("/api/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderType:orderType==="dining"?"Dining":"Parcel",items,foodTotal:t.food,parcelCharge:t.parcel,total:t.total,notes:document.getElementById("notesInput").value.trim()})});const d=await r.json();if(!r.ok||!d.orderNumber)throw Error(d.error||"Order failed");let msg=`🍽️ *FOOD ON WHEELS*\\n\\n🔢 *ORDER #${d.orderNumber}*\\n📦 Type: ${orderType==="dining"?"Dining":"Parcel"}\\n\\n`;items.forEach(i=>msg+=`• ${i.name} × ${i.quantity} = ₹${i.lineTotal}\\n`);msg+=`\\n💰 Food total: ₹${t.food}`+(t.parcel?"\\n📦 Parcel charge: ₹10":"")+`\\n💵 *TOTAL: ₹${t.total}*`;const notes=document.getElementById("notesInput").value.trim();if(notes)msg+=`\\n\\n📝 *Special instructions:* ${notes}`;msg+="\\n\\nPlease prepare the order.";location.href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`}catch(e){console.error(e);alert("We couldn't create the order number. Please try again.");btn.disabled=false;btn.textContent="Send Order on WhatsApp →"}}
document.querySelectorAll(".type").forEach(b=>b.addEventListener("click",()=>setType(b.dataset.type)));
document.getElementById("whatsappButton").addEventListener("click",sendWhatsApp);
renderMenu();updateCart();