const WHATSAPP_NUMBER="919010185837",RESTAURANT_NAME="Food On Wheels";
const menuData=[
["French Fries",[["Mini Fries",49],["Salted Fries",70],["Peri Peri Fries",75],["Salted Cheesy Fries",90],["Peri Peri Cheesy Fries",99],["Paneer Loaded Fries",129],["Chicken Loaded Fries",139],["Cheesy Chicken Loaded Fries",149]]],
["Burgers",[["Veg Burger",70],["Paneer Burger",100],["Egg Burger",75],["Egg Chicken Burger",109],["Classic Chicken Burger",95],["Chicken Crispy Burger",110],["Popcorn Chicken Burger",100],["SPL Chicken Burger",120],["SPL Chicken Burger with Cheese",140],["Crispy No Bun Chicken Burger",179]]],
["Rolls",[["Veg Roll",70],["Paneer Roll",100],["Egg Roll",75],["Egg Chicken Roll",100],["Crispy Chicken Roll",110],["Popcorn Chicken Roll",100],["SPL Chicken Roll",120]]],
["Bread Omelette",[["Bread Omelette",70],["Bread Omelette with Cheese",89],["Egg Chicken Bread Omelette",110],["Egg Chicken Bread Omelette with Cheese",129]]],
["Pav Bajji",[["Mushroom Pav Bajji",110],["Paneer Pav Bajji",129],["Egg Pav Bajji",110],["Chicken Pav Bajji",129],["Egg Chicken Pav Bajji",149]]],
["Starters",[["Veg Fingers (6)",79],["Paneer Popcorn (100gms)",119],["Paneer Fingers (6)",119],["Cheese Corn Nuggets (6)",99],["Chicken Nuggets (6)",89],["Chicken Fingers (6)",99],["Chicken Cheese Balls (6)",110],["Chicken Popcorn (130gms)",120],["Crispy Chicken Lollipop (5)",110],["Chicken Lollipop (Kabab Style)",110],["Crispy Chicken Chips",139],["Crispy Chicken Fries",139]]],
["Pizzas",[["Cheese Blast",99],["Cheese & Corn Pizza",120],["Mushroom Pizza",120],["Paneer Pizza",130],["Paneer Corn Pizza",140],["Chicken Pizza",140],["Chicken Keema Pizza",160],["Chicken Corn Pizza",150]]],
["Sandwich Menu",[["Mix Veg Sandwich",80],["Corn & Cheese Sandwich",90],["Mushroom Sandwich",100],["Paneer Sandwich",100],["Paneer Cheese Sandwich",120],["Chicken Sandwich",120],["Chicken & Cheese Sandwich",140],["Crispy Chicken Sandwich",120]]],
["Devil Eggs",[["Crispy Devil Eggs - Green Masala (6)",120],["Crispy Devil Eggs - Thadoori Masala (6)",120]]],
["Mojito's",[["Lemon Sprite",59],["Lemon Mint",69],["Blue Coraco",69],["Strawberry",69],["Pinacola",69]]],
["Burger Combo",[["Veg Burger + Fries + Mojito",110],["Veg Burger + Fries + Mojito + 2 Fingers",170],["Paneer Burger + Mojito",160],["Egg Burger + Fries + Mojito",150],["Classic Chicken Burger + Fries + Mojito",170],["Crispy Chicken Burger + Mojito or Fries",160],["Crispy Chicken Burger + Fries + Mojito",180],["SPL Chicken Burger + Fries + Mojito",230]]],
["Rolls Combo",[["Veg Roll + Fries + Mojito + 2 Fingers",170],["Paneer Roll + Mojito or Fries",160],["Egg Roll + Fries + Mojito",170],["Crispy Chicken Roll + Fries or Mojito",160],["Crispy Chicken Roll + Fries + Mojito + 2pcs Chicken Lollipop",210],["Popcorn Chicken Roll + Mojito",200]]],
["Sandwich Combo",[["Mix Veg Sandwich + Fries + Mojito + Cheese & Corn Nuggets (3pcs)",190],["Corn & Cheese Sandwich + Fries + Mojito",170],["Chicken Sandwich + Fries + Mojito + 2 Fingers + 2 Lollipops",240],["Chicken Cheese Sandwich + Fries + Mojito + 2 Lollipops",270]]]
];
let n=0,orderType="dining",cart={};const $=s=>document.querySelector(s),slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),money=n=>Number(n).toLocaleString("en-IN");
const queryMap={"French Fries":"french fries","Burgers":"burger","Rolls":"indian roll","Bread Omelette":"omelette","Pav Bajji":"pav bhaji","Starters":"chicken starter","Pizzas":"pizza","Sandwich Menu":"sandwich","Devil Eggs":"deviled eggs","Mojito's":"fruit mojito","Burger Combo":"burger combo","Rolls Combo":"chicken roll","Sandwich Combo":"sandwich combo"};
function normalize(){return menuData.map(([cat,items])=>({name:cat,items:items.map(([name,price])=>({id:slug(cat+"-"+name),name,price,diningOnly:cat.includes("Combo"),image:`https://loremflickr.com/640/480/${encodeURIComponent(queryMap[cat]||cat)}/${encodeURIComponent(name.split(" ").slice(0,3).join(" "))}?lock=${++n}`}))}));}const menu=normalize(),all=()=>menu.flatMap(c=>c.items),item=id=>all().find(i=>i.id===id);
function renderMenu(){$("#categories").innerHTML=menu.map(c=>`<button class="chip" data-chip="${slug(c.name)}" onclick="jump('${slug(c.name)}')">${c.name}</button>`).join("");$("#menu").innerHTML=menu.map(c=>`<section class="category" id="cat-${slug(c.name)}"><h2>${c.name}</h2>${c.items.map(i=>`<div class="item"><img class="food-img" loading="lazy" src="${i.image}" alt="${i.name}" onerror="this.style.visibility='hidden'"><div class="info"><h3>${i.name}${i.diningOnly?'<span class="tag">DINING ONLY</span>':''}</h3><div class="price">₹${money(i.price)}</div></div><div class="action" data-action="${i.id}"></div></div>`).join("")}</section>`).join("");all().forEach(i=>renderAction(i.id));}
function renderAction(id){const e=document.querySelector(`[data-action="${id}"]`),q=cart[id]||0;if(e)e.innerHTML=q?`<div class="qty"><button onclick="changeQty('${id}',-1)">−</button><b>${q}</b><button onclick="changeQty('${id}',1)">+</button></div>`:`<button class="add" onclick="changeQty('${id}',1)">ADD</button>`}
function jump(id){document.getElementById("cat-"+id)?.scrollIntoView({behavior:"smooth",block:"start"})}
function changeQty(id,d){const i=item(id);if(!i)return;if(orderType==="parcel"&&i.diningOnly&&d>0)return alert("This combo is available for dining only.");cart[id]=Math.max(0,(cart[id]||0)+d);if(!cart[id])delete cart[id];renderAction(id);updateCart()}
function totals(){let count=0,food=0,parcelItems=0;Object.entries(cart).forEach(([id,q])=>{const i=item(id);if(i){count+=q;food+=q*i.price;if(orderType==="parcel")parcelItems+=q}});const parcel=orderType==="parcel"?parcelItems*10:0;return{count,food,parcel,parcelItems,total:food+parcel}}
function updateCart(){const t=totals();$("#cartButton").hidden=!t.count;$("#cartCount").textContent=t.count;$("#cartItemsLabel").textContent=`${t.count} ${t.count===1?"item":"items"}`;$("#cartTotal").textContent=money(t.total);$("#foodTotal").textContent=money(t.food);$("#parcelTotal").textContent=money(t.parcel);$("#modalTotal").textContent=money(t.total);$("#parcelLine").hidden=!t.parcel}
function renderCart(){$("#cartItems").innerHTML=Object.entries(cart).map(([id,q])=>{const i=item(id);return`<div class="cart-row"><div><b>${i.name}</b><small>₹${money(i.price)} × ${q}</small></div><div class="row-actions"><button onclick="changeQty('${id}',-1)">−</button><b>${q}</b><button onclick="changeQty('${id}',1)">+</button></div></div>`}).join("")||`<div class="empty">Your cart is empty.</div>`}
function openCart(){renderCart();$("#cartModal").hidden=false;document.body.style.overflow="hidden"}function closeCart(){$("#cartModal").hidden=true;document.body.style.overflow=""}
function setType(t){orderType=t;document.querySelectorAll(".type").forEach(b=>b.classList.toggle("active",b.dataset.type===t));$("#parcelNote").style.display=t==="parcel"?"block":"none";if(t==="parcel")Object.keys(cart).forEach(id=>{if(item(id)?.diningOnly)delete cart[id]});all().forEach(i=>renderAction(i.id));updateCart();renderCart()}
function msg(orderNumber,items,t,notes){const a=[`🍽️ *${RESTAURANT_NAME.toUpperCase()}*`,``,`🔢 *ORDER #${orderNumber}*`,`📦 Type: ${orderType==="dining"?"Dining":"Parcel"}`,``];items.forEach(i=>a.push(`• ${i.name} × ${i.quantity} = ₹${i.lineTotal}`));a.push(``,`💰 Food total: ₹${t.food}`);if(t.parcel)a.push(`📦 Parcel charge: ₹${t.parcel} (${t.parcelItems} × ₹10)`);a.push(`💵 *TOTAL: ₹${t.total}*`);if(notes)a.push(``,`📝 *Special instructions:* ${notes}`);a.push(``,`Please prepare the order.`);return a.join("\n")}
async function sendWhatsApp(){const t=totals();if(!t.count)return alert("Please add at least one item.");const notes=$("#notesInput").value.trim(),items=Object.entries(cart).map(([id,q])=>{const i=item(id);return{name:i.name,quantity:q,unitPrice:i.price,lineTotal:i.price*q}}),b=$("#whatsappButton"),old=b.innerHTML;b.disabled=true;b.innerHTML="Generating order… ⏳";try{const r=await fetch("/api/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderType:orderType==="dining"?"Dining":"Parcel",items,foodTotal:t.food,parcelCharge:t.parcel,total:t.total,notes})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.orderNumber)throw Error(d.error||"Could not create order");location.href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg(d.orderNumber,items,t,notes))}`}catch(e){console.error(e);alert("We couldn't create the order number. Please try again.");b.disabled=false;b.innerHTML=old}}
$("#startOrdering").onclick=()=>$("#menuArea").scrollIntoView({behavior:"smooth"});document.querySelectorAll(".type").forEach(b=>b.onclick=()=>setType(b.dataset.type));$("#cartButton").onclick=openCart;$("#closeCart").onclick=closeCart;$("#whatsappButton").onclick=sendWhatsApp;$("#cartModal").onclick=e=>{if(e.target===$("#cartModal"))closeCart()};renderMenu();updateCart();
